### ISSUE TITLE
General overview

### ISSUE THREAD

**Issue by lpalbou** [geneontology/archive-reconstruction#5]
Current data archive of GO is scattered across 3 ressources: SVN, CVS and archive.geneontology.org

GO data archive links:
- svn: http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/
- archive: http://archive.geneontology.org
- cvs: http://cvsweb.geneontology.org/

Archive retrieval:
- [x] Get SVN copy: https://github.com/geneontology/operations/issues/35
- [x] Get archive copy: https://github.com/geneontology/operations/issues/36
- [x] Get CVS copy: https://github.com/geneontology/operations/issues/34

Archive reconstruction:
- [x] reconstruction from SVN: https://github.com/geneontology/archive-reconstruction/issues/1
- [x] reconstruction from archive: get sql dumps + possibly reconstruct obo files from obo-xml present since 2005) https://github.com/geneontology/archive-reconstruction/issues/6
- [x] reconstruction from CVS: old OBOs GAFs are present here too https://github.com/geneontology/archive-reconstruction/issues/7

- [ ] polishing: https://github.com/geneontology/archive-reconstruction/issues/8

**Comment by lpalbou** [comment]
Close in favor of https://github.com/geneontology/archive-reconstruction/issues/9
